/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gpu_GPU */

#ifndef _Included_gpu_GPU
#define _Included_gpu_GPU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gpu_GPU
 * Method:    initializeMersenneTwister
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_gpu_GPU_initializeMersenneTwister
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
