/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OpenCLRandom_OpenCLMersenneTwister */

#ifndef _Included_OpenCLRandom_OpenCLMersenneTwister
#define _Included_OpenCLRandom_OpenCLMersenneTwister
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OpenCLRandom_OpenCLMersenneTwister
 * Method:    initializeMersenneTwister
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_OpenCLRandom_OpenCLMersenneTwister_initializeMersenneTwister
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
